export const themes = {
    light: {
        background: '#FFFFFF',
        tabbackground: '#FFFFFF',
        text: '#000000',
        subheader: '',
        activeIcon: '#000',
        inactiveIcon: '#999',
        primary: '#1A80E5',
        secondary: '#5856D6',
        border: '#E5E5EA',
        card: '#F2F2F7',
    },
    dark: {
        background: '#121212',
        tabbackground: '#363636',
        text: '#FFFFFF',
        subheader: '#a4a4a6',
        activeIcon: '#FFFFFF',
        inactiveIcon: '#FDFCFA',
        primary: '#8875FF',
        secondary: '#5E5CE6',
        border: '#979797',
        input: '#1D1D1D',
        card: '#1C1C1E',
    },
};